### ISSUE TITLE
how does this model deal with out of context words and words of languages other than English?

### ISSUE THREAD

**Issue by Tuo-ZHANG** [pierluigic/xl-lexeme#1]
Hi there,
I would be grateful if you could explain a little about these two questions. Many thanks!

**Comment by pierluigic** [comment]
Hi,

By out of context words do you refer to word without context? That is, creating a vector representation only by considering the word without a reference sentence?

The model was tested for the LSCD task for Swedish, German and Russian. The results are available in the article https://aclanthology.org/2023.acl-short.135.pdf

**Comment by Tuo-ZHANG** [comment]
> Hi,
> 
> By out of context words do you refer to word without context? That is, creating a vector representation only by considering the word without a reference sentence?
> 
> The model was tested for the LSCD task for Swedish, German and Russian. The results are available in the article https://aclanthology.org/2023.acl-short.135.pdf

Sorry, I have wrongly phrased the question. My question is that how the model would handle out of vocabulary words. In Bert, out of vocabulary words would be split, which means, a single word  could be split into subwords and embeddings for subwords would be created, how will your model handle this case? Thanks!

**Comment by pierluigic** [comment]
Also in XL-LEXEME OOV words will be split into subwords, since XL-LEXEME rely on XLM-R. The final word representation is obtained by averaging the subword vectors.

**Comment by Tuo-ZHANG** [comment]
> Also in XL-LEXEME OOV words will be split into subwords, since XL-LEXEME rely on XLM-R. The final word representation is obtained by averaging the subword vectors.

Now I understand, thanks!
