### ISSUE TITLE
does this model have a length restriction on sentence input?

### ISSUE THREAD

**Issue by Tuo-ZHANG** [pierluigic/xl-lexeme#2]
I was wondering what would happen if the input sentence is too long, I mean, when the sentence have too many tokens, would the model still be able to handle that?

Regards,
Tuo ZHANG

**Comment by pierluigic** [comment]
The sentence will be automatically truncated

**Comment by choppa98** [comment]
Hi, can you state the logic behind truncation? If the target word occurs at the end of the sentence, in what fashion is the sentence truncated?

**Comment by pierluigic** [comment]
The goal of truncation is to eliminate subword tokens from both the beginning and end of a sentence, ensuring that the total number of subword tokens does not exceed the maximum permitted length while always preserving the target word. For example, in situations where the target word is at the very end of the sentence, truncation will only occur at the beginning. For a comprehensive explanation, refer to the paper available at [https://aclanthology.org/2023.acl-short.135.pdf](https://aclanthology.org/2023.acl-short.135.pdf).
